replicaCount: 1

image:
  ## ToDo: add registery
  #repository: digikala-node-app
  path: /home/vagrant/digikala-node-app.tar
  tag: latest
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "100m"

service:
  name: digikala-node-app
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: digikala-node-app.local
      paths:
        - "/"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

healthCheckPath: "/"

nodeSelector: {}
tolerations: []
affinity: {}
