apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simple-node-app-chart.fullname" . }}
  labels:
    app: {{ include "simple-node-app-chart.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "simple-node-app-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "simple-node-app-chart.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{ toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: "{{ .Values.healthCheckPath }}"
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: "{{ .Values.healthCheckPath }}"
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-node-app-chart.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
  selector:
    app: {{ include "simple-node-app-chart.name" . }}
