apiVersion: v1
kind: Secret
metadata:
  name: ghcr-pull-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiU2hhbWltU2hhaHJhZWluaSIsInBhc3N3b3JkIjoiZ2hwX0dmQ1FEQm93UEpMME9xZzV3bERGOUN1NHBpREVwTzBRcEs4ZSIsImF1dGgiOiJVMmhoYldsdFUyaGhhSEpoWldsdWFUcG5hSEJmUjJaRFVVUkNiM2RRU2t3d1QzRm5OWGRzUkVZNVEzVTBjR2xFUlhCUE1GRndTemhsIn19fQ==